apiVersion: apps/v1
kind: Deployment
metadata:
  name: nike-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nike-clone
  template:
    metadata:
      labels:
        app: nike-clone
    spec:
      containers:
      - name: nike-clone
        image: mohsin01/nike-clone
        ports:
        - containerPort: 3000
